build_info:
  python_version: '3.11'
concepts:
- id: '0'
  name: bee-worker
- id: '1'
  name: bee-drone
- id: '2'
  name: bee-worker-occluded
- id: '3'
  name: bee-queen
inference_compute_info:
  accelerator_memory: 5Gi
  accelerator_type:
  - NVIDIA*
  cpu_limit: '4'
  cpu_memory: 2Gi
  num_accelerators: 1
model:
  app_id: local-dev-runner-app
  id: local-dev-model
  model_type_id: visual-detector
  user_id: gratheon
