services:
  models-bee-detector:
    build:
      context: .
      dockerfile: Dockerfile.prod
    # command: python3 /app/server.py # Removed, CMD is in Dockerfile now
    environment:
      - ENV_ID=prod
    ports:
      - 8700:8700
    # volumes: # Removed, code is copied in Dockerfile now
    #   - .:/app/
    restart: always
