# FROM dustynv/l4t-pytorch:r36.2.0
FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libsm6 \
    libxext6 \
    libgomp1 \
    libgl1 \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip cache purge && \
    rm -rf /root/.cache/pip

COPY . /app/
RUN ls /app/weights

EXPOSE 8700

# CMD ["python3", "/app/server.py"]
