services:
  models-bee-detector:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      python3 /app/server.py
    environment:
      - ENV_ID=dev
    ports:
      - 8700:8700
    volumes:
      - .:/app/
    restart: always
