#version: '3.9'
services:
  models-bee-detector:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      ddtrace-run python3 /app/server.py
    environment:
      - ENV_ID=dev
      - DD_SERVICE=models-bee-detector
      - DD_ENV=dev
      - DD_PROFILING_ENABLED=false
    ports:
      - 8700:8700
    volumes:
      - .:/app/
    restart: always
